### ISSUE TITLE
Error help!

### ISSUE THREAD

**Issue by Karan326** [codeMoriarity/Track-your-Fit#1]
Sir I am also making a running tracker app, but got this error 2 days back and couldnt able to solve it yet, so could you please help

Error is in inflating class google android material bottom navigation
I tried stackoverflow, youtube, but it didnt work

**Comment by codeMridul** [comment]
Change your AppTheme parent to Theme.MaterialComponents

Before

```
<!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
    </style>
```
   
After

    ```
<!-- Material application theme. -->
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        <!-- Customize your theme here. -->
    </style>
```

**Comment by Karan326** [comment]
Actually sir i made wrong vector files, thats why I got that error.
But thank you so much for replying.
hope you won't mind if I text you in future for any query!
